<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <base href="<?php echo $config['base_url'] ?>">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <style>
    
    .masthead {
      height: 100vh;
      min-height: 500px;
      background-image: url('https://source.unsplash.com/BtbjCFUvBXs/1920x1080');
      background-size: cover;
      background-attachment: fixed;
      background-position: center;
      background-repeat: no-repeat;
    }
    
    </style>

    <title>System or Site name</title>
  </head>
  <body>

 <!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow fixed-top">
  <div class="container">
    <a class="navbar-brand" href="<?php echo $config['base_url'] ?>">Start Bootstrap</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">

        <!-- <li class="nav-item">
          <a class="nav-link" href="/">Home </a>
        </li>
              <li class="nav-item">
          <a class="nav-link" href="sobre/">Sobre Nós </a>
        </li>
              <li class="nav-item">
          <a class="nav-link" href="produtos/">Produtos </a>
        </li>
              <li class="nav-item">
          <a class="nav-link" href="contato/">Fale Conosco </a>
        </li> -->

      <?php 
        /** 
         * For test purpose, if want menu from Database:
         *      
        */
      ?>

              <?php 
                use App\Connection;
                $db = Connection::pdo();
                $data = $db->query('SELECT `Name`,`Permalink` FROM tab_menu ORDER BY `Ordem` ASC')->fetchAll();

                //Print menu's from Database
                //Only tests purpose
                //You can write menu manually in HTML
                //You can run your own query's
                foreach($data as $key => $val):
              ?>
                <li class="nav-item">
                  <a class="nav-link" href="<?php echo $val['Permalink'] ?>"><?php echo $val['Name'] ?> </a>
                </li>
              <?php endforeach; ?>
      </ul>
    </div>
  </div>
</nav>

  <?php 
      //Content of page from Controller
      $this->render($this->view->body)
  ?>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
</html>